# Fichier: application-local.properties
# Ce fichier contient les secrets pour l'environnement de développement local.
# Il n'est pas versionné dans Git.

# Secret pour la base de données
spring.datasource.password=root

# Secret pour le JWT
jwt.secret=MaCleJWTSecreteEtLonguePourLeDeveloppementLocal1234567890!

# Mot de passe d'application pour Gmail
spring.mail.password=txrhranpwyyicfgz
