spring.application.name=stagefinder

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/stagefinder
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Paramètres Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=public

# Logging (optionnel)
logging.level.org.springframework.security=DEBUG
logging.level.com.stagefinder=DEBUG

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Désactiver la sérialisation par défaut sous forme de tableau
spring.jackson.serialization.write-dates-as-timestamps=false

# (Optionnel) Définir un format par défaut (ISO 8601)
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

# Activez Swagger UI
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html


# Solution pour Spring Boot 3+
#spring.mvc.pathmatch.matching-strategy=ant_path_matcher