package ma.stagefinder.entities.enums;

public enum Ville {
    AGADIR, ALHOCEIMA, AZILAL, AZROU, BÉNIMELLAL, BERKANE, BOUJDOUR, CASABLANCA, CHEFCHAOUEN, DAHLIA,
    ELHAJEB, ELJADIDA, ERRACHIDIA, ESSAOUIRA, FÈS, FIGUIG, GUELMIM, IFRANE, IMIZOUR, KÉNITRA, KHÉNIFRA,
    KHOURIBGA, LAÂYOUNE, LARACHE, MARRAKECH, MEKNÈS, MIDELT, MOHAMMÉDIA, NADOR, OUARZAZATE, OUJDA, OUEDZEM,
    RABAT, SAFI, SALE, SEFROU, SETTAT, SIDIKACEM, SIDISLIMANE, SKHIRAT, TANGER, TANTAN, TAROUDANT, TATA,
    TAOURIRT, TAZA, TÉTOUAN, TINGHIR, TIZNIT, YOUSSOUFIA, ZAGORA
}
